In [1]:
import glob
import numpy as np
import scanpy as sq
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed
import scanpy as sc
from tqdm import tqdm
import yaml

In [2]:
with open("../config.yaml", "r") as stream:
    DATASET_INFO = yaml.safe_load(stream)
DATASET_INFO

{'DATASET_NAME': {'10x_TuPro': 'Tumor Profiler (n=18)',
  'SCCRCC': 'Kidney cancer (n=24)',
  'COAD': 'Colon cancer (HEST1K) (n=8)',
  'USZ': 'Kidney/Lung with TLS (n=6)',
  'LUNG_CANCER': 'Lung cancer (HEST1K) (n=36)',
  'Lung_Xenium': 'Lung cancer (10x Xenium) (n=17)',
  'TCGA_SKCM_ffpe': 'TCGA SKCM (FFPE)',
  'TCGA_SKCM_ff': 'TCGA SKCM (FF)',
  'TCGA_KIRC_ffpe': 'TCGA KIRC (FFPE)',
  'TCGA_KIRC_ff': 'TCGA KIRC (FF)',
  'TCGA_LUAD_ffpe': 'TCGA LUAD (FFPE)',
  'TCGA_LUAD_ff': 'TCGA LUAD (FF)',
  'TCGA_LUSC_ffpe': 'TCGA LUSC (FFPE)',
  'TCGA_LUSC_ff': 'TCGA LUSC (FF)'}}

In [3]:
# Function to read a file and return the number of spots
def get_n_spots(file):
    
    adata = sc.read_h5ad(file, backed="r")
    if "bulk_norm_tpm_unstranded" in adata.var.columns:
        observed_bulk = adata.var.bulk_tpm_unstranded
    else:
        observed_bulk = []
    n = len(adata)
        
    
    return n, observed_bulk

In [4]:
import torch
num_workers = torch.get_num_threads()
num_workers

10

In [5]:
datasets = DATASET_INFO["DATASET_NAME"].keys()
datasets = [d for d in datasets if "Xenium" not in d]
datasets

['10x_TuPro',
 'SCCRCC',
 'COAD',
 'USZ',
 'LUNG_CANCER',
 'TCGA_SKCM_ffpe',
 'TCGA_SKCM_ff',
 'TCGA_KIRC_ffpe',
 'TCGA_KIRC_ff',
 'TCGA_LUAD_ffpe',
 'TCGA_LUAD_ff',
 'TCGA_LUSC_ffpe',
 'TCGA_LUSC_ff']

In [6]:
data = []
for dataset in datasets:
    if "TCGA" in dataset:
        slide_type = dataset.split("_")[-1]
        dataset_name = dataset.replace(f"_{slide_type}", "")
        print(dataset_name, slide_type)
        metadata = pd.read_csv(f"../{dataset_name}/data/metadata_{slide_type}.csv")
        metadata = metadata[~metadata.image_path.duplicated()]
        metadata = metadata.set_index("id_pair")
        files = glob.glob(f'../{dataset_name}/out_benchmark_{slide_type}/data/h5ad/*.h5ad')
        files = np.array(files)
        files = files[np.array([int(i.split("/")[-1].split(".")[0]) in metadata.index for i in files])]

    else:
        files = glob.glob(f'../{dataset}/out_benchmark/data/h5ad/*.h5ad')
    files = [f for f in files if "all" not in f]
    observed_bulk = []
    n_spots_per_sample = []
    
    # Using ProcessPoolExecutor to parallelize the processing
    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        # Submit all file processing tasks
        
        futures = [executor.submit(get_n_spots, f) for f in files]
    
        # Collect results as they complete
        for future in tqdm(as_completed(futures), total=len(files)):
            n, bulk = future.result()
            n_spots_per_sample.append(n)
            observed_bulk.append(bulk)

        n_spots_per_sample_df = pd.DataFrame(n_spots_per_sample, columns=["spots_per_sample"])
        n_spots_per_sample_df['dataset'] = dataset

    data.append([dataset, len(files), np.nansum(n_spots_per_sample)])
data = pd.DataFrame(data, columns=["dataset", 'samples', 'spots'])
data

100%|██████████| 18/18 [00:00<00:00, 22.39it/s]
100%|██████████| 24/24 [00:01<00:00, 21.59it/s]
100%|██████████| 8/8 [00:01<00:00,  7.67it/s]
100%|██████████| 8/8 [00:00<00:00, 17.74it/s]
100%|██████████| 36/36 [00:01<00:00, 30.66it/s]

TCGA_SKCM ffpe

100%|██████████| 276/276 [00:27<00:00,  9.97it/s]

TCGA_SKCM ff

100%|██████████| 472/472 [00:25<00:00, 18.45it/s]

TCGA_KIRC ffpe

100%|██████████| 516/516 [00:52<00:00,  9.92it/s]

TCGA_KIRC ff

100%|██████████| 528/528 [00:28<00:00, 18.57it/s]

TCGA_LUAD ffpe

100%|██████████| 525/525 [00:54<00:00,  9.55it/s]

TCGA_LUAD ff

100%|██████████| 537/537 [00:25<00:00, 21.20it/s]

TCGA_LUSC ffpe

100%|██████████| 471/471 [00:41<00:00, 11.34it/s]

TCGA_LUSC ff

100%|██████████| 455/455 [00:21<00:00, 21.33it/s]

           dataset  samples     spots
0        10x_TuPro       18     80335
1           SCCRCC       24     74220
2             COAD        8      8985
3              USZ        8     24246
4      LUNG_CANCER       36     83625
5   TCGA_SKCM_ffpe      276   2461800
6     TCGA_SKCM_ff      472    791235
7   TCGA_KIRC_ffpe      516  33071970
8     TCGA_KIRC_ff      528   1515775
9   TCGA_LUAD_ffpe      525   7913875
10    TCGA_LUAD_ff      537   1769046
11  TCGA_LUSC_ffpe      471   7241441
12    TCGA_LUSC_ff      455   1527552

In [7]:
data["data_type"] = data.dataset.apply(lambda x: "Digital ST" if "TCGA" in x else "Visium,\n10x Genomics")
data

           dataset  samples     spots              data_type
0        10x_TuPro       18     80335  Visium,\n10x Genomics
1           SCCRCC       24     74220  Visium,\n10x Genomics
2             COAD        8      8985  Visium,\n10x Genomics
3              USZ        8     24246  Visium,\n10x Genomics
4      LUNG_CANCER       36     83625  Visium,\n10x Genomics
5   TCGA_SKCM_ffpe      276   2461800             Digital ST
6     TCGA_SKCM_ff      472    791235             Digital ST
7   TCGA_KIRC_ffpe      516  33071970             Digital ST
8     TCGA_KIRC_ff      528   1515775             Digital ST
9   TCGA_LUAD_ffpe      525   7913875             Digital ST
10    TCGA_LUAD_ff      537   1769046             Digital ST
11  TCGA_LUSC_ffpe      471   7241441             Digital ST
12    TCGA_LUSC_ff      455   1527552             Digital ST

In [8]:
data.query("data_type == 'Digital ST'")["spots"].sum()

56292694

In [9]:
data.query("data_type == 'Digital ST'")["samples"].sum()

3780

In [ ]:
DATASET_INFO['DATASET_NAME']

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 18})
# Data
datasets = [DATASET_INFO['DATASET_NAME'][d].split(" (n")[0].replace(' with', '\nwith').replace(' (F', '\n(F').replace(' (HEST1K)', '') for d in data.dataset.values]
samples = data.samples.values
spots = data.spots.values
data_type = data.data_type.values

# Define colors for different data types
color_map = {
    'Visium,\n10x Genomics': 'lightblue',
    'Digital ST': 'gray',
}

# Convert spots to millions for better readability
spots_millions = [s for s in spots]

# Sort by data_type first (Visium, 10x Genomics first), then by number of spots
sorted_indices = sorted(range(len(spots)), key=lambda i: (data_type[i] != 'Visium,\n10x Genomics', -spots[i]))
sorted_datasets = [datasets[i] for i in sorted_indices]
sorted_samples = [samples[i] for i in sorted_indices]
sorted_spots_millions = [spots_millions[i] for i in sorted_indices]
sorted_data_type = [data_type[i] for i in sorted_indices]

# Assign colors based on data type
colors = [color_map[dt] for dt in sorted_data_type]

# Create a figure and axis with increased width
fig, ax = plt.subplots(figsize=(18, 9))  # Adjust width (12) and height (6) as needed

# Create bar chart with colors based on data type
bars = ax.bar(sorted_datasets, sorted_spots_millions, color=colors)

# Annotate bars with the number of samples
for bar, sample in zip(bars, sorted_samples):
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2, yval, f'(n={sample})', 
            ha='center', va='bottom', color='blue')

# Add labels and title
ax.set_xlabel('Dataset', fontsize=30)
ax.set_ylabel('Spots', fontsize=30)
#ax.set_title('Number of Spots by Dataset')
# Rotate x-axis labels 90 degrees
plt.xticks(rotation=60)
# Customize y-axis to show 'M' for millions
ax.set_yscale('log')

# Create custom legend
legend_patches = [mpatches.Patch(color=color, label=label) for label, color in color_map.items()]
ax.legend(handles=legend_patches, title="")
plt.savefig('figures/Figure6A-dataset_size.png', dpi=300, bbox_inches = 'tight')
# Show the plot
plt.show()